sim = true
project_id = 17323
# tool = 'mean-app'

[debug]
nodeps = false
timeout = 60


[[clients]]
fc_username = 'federated.client+00@gmail.com'
data = ["data/A/data.csv", "config.yml"]
coordinator = true


[[clients]]
fc_username = 'federated.client+01@gmail.com'
data = ["data/B/data.csv", "config.yml"]


[[clients]]
fc_username = 'federated.client+02@gmail.com'
data = ["data/C/data.csv", "config.yml"]




