[general]
outdir = "results/biosphere/random-forest/fed/"
project_id = 17308

[debug]
nodeps = true
reinstall = true
timeout = 600
[clients.0]
coordinator = true
fc_username = "federated.client+00@gmail.com"
hostname = "134.158.249.201"
username = "ubuntu"
sshkey = "/home/lweilguny/.ssh/biosphere"
data = ["data/random-forest/PRJEB10878/input.csv", "configs/biosphere/random-forest/config.yml"]

[clients.1]
fc_username = "federated.client+01@gmail.com"
hostname = "134.158.249.180"
username = "ubuntu"
sshkey = "/home/lweilguny/.ssh/biosphere"
data = ["data/random-forest/PRJEB6070/input.csv", "configs/biosphere/random-forest/config.yml"]

[clients.2]
fc_username = "federated.client+02@gmail.com"
hostname = "134.158.249.153"
username = "ubuntu"
sshkey = "/home/lweilguny/.ssh/biosphere"
data = ["data/random-forest/PRJEB7774/input.csv", "configs/biosphere/random-forest/config.yml"]

[clients.3]
fc_username = "federated.client+03@gmail.com"
hostname = "134.158.249.37"
username = "ubuntu"
sshkey = "/home/lweilguny/.ssh/biosphere"
data = ["data/random-forest/PRJNA429097/input.csv", "configs/biosphere/random-forest/config.yml"]

[clients.4]
fc_username = "federated.client+04@gmail.com"
hostname = "134.158.248.68"
username = "ubuntu"
sshkey = "/home/lweilguny/.ssh/biosphere"
data = ["data/random-forest/PRJNA731589/input.csv", "configs/biosphere/random-forest/config.yml"]
