# config for the random-forest app. 
# Needs to be named config.yml (hardcoded in the app)
fc_random_forest:
  input:
    train: "species.csv"
    test: "species.csv"
  output:
    pred: "pred.csv"
    proba: "proba.csv"
    test: "test.csv"
  format:
    sep: ","
    label: "health_status"
  split:
    mode: file # directory if cross validation was used before, else file
    dir: . # data if cross validation app was used before, else .
  estimators: 100 # number of trees in the forest
  mode: classification # classification or regression
  random_state: 42 # random state for reproducibility
