fc_pca:
  algorithm:
    pcs: 10   # retrieve 10 Eigenvectors
  input:
    dir: '' # In which directory is the data located
    data: species_header_index_nostatus.csv   # name of the input file (required)
    delimiter: ","  # field separator in the input file 
  output:
    dir: pca # output will be saved in a directory called 'pca'
    eigenvalues: eigenvalues.tsv
    left_eigenvectors: left_eigenvectors.tsv
    projections: localData.csv
    right_eigenvectors: right_eigenvectors.tsv
    scaled_data_file: scaled_data.tsv
    variance_explained_file: variance_explained.csv
  privacy:
    send_projections: false # if false, no projections are shared.
    subsample_projections: false # if true, sampled projections are sent, instead of the real ones.
  scaling:
    center: true # substract mean from each variable
    highly_variable: false # select highly variable genes
    log_transform: true # log transform data prior to computation (make sure the data does not contain negative entries)
    max_nan_fraction: 1 # remove variables with more than 100*man_nan_fraction% NAs. 
    perc_highly_var: 0.9 # select the top 100*perc_highly_var% highly variable genes.
    variance: true # scale to unit variance (devide trough standard deviation)

