downsample_features: 0.05
metadata: 'metadata_2340_CRC_cohort_20240704'
species_signal: 'species_signal_2340_CRC_cohort_20240617_combat_prev0'
accessions: [
  "PRJEB10878",
  "PRJEB6070",
  "PRJEB7774",
  "PRJNA429097",
  "PRJNA731589",
]
# Names of tools to be run in the workflow
# for each, config files need to be present as:
#      resources/<tool>/config_fedsim_cent.toml
#      resources/<tool>/config_fedsim_fed.toml
tools: ["federated-svd", "random-forest"] #, "ada-boost"]
