[clients]


[clients.client0]
data = ["data/federated_svd_split/mnist_split_0.txt", "data/federated_svd_split/config.yaml"]
hostname = 'localhost'
username = 'user'
port = '2222'
coordinator = true

[clients.client1]
data = ["data/federated_svd_split/mnist_split_1.txt", "data/federated_svd_split/config.yaml"]
hostname = 'localhost'
username = 'user'
port = '2223'

[clients.client2]
data = ["data/federated_svd_split/mnist_split_2.txt", "data/federated_svd_split/config.yaml"]
hostname = 'localhost'
username = 'user'
port = '2224'


[project]
pid = 17264


[vm]
target_dir = '/home/user/data'

