[clients]


[clients.client0]
data = ["data/federated_svd_split/mnist_split_0.tsv", "data/federated_svd_split/config.yaml"]
hostname = '192.168.121.128'
username = 'vagrant'
port = '' # not needed for biosphere
coordinator = true


[project]
pid = 17268


[vm]
target_dir = '/home/vagrant/fedsim'

