[clients]


[clients.client0]
data = ["data/federated_svd_split/mnist_split_0.tsv", "data/federated_svd_split/config.yaml"]
hostname = '134.158.249.96'
username = 'ubuntu'
port = '' # not needed for biosphere
coordinator = true


[project]
pid = 17268


[vm]
target_dir = '/home/ubuntu/fedsim'

