[general]
sim = true
outdir = "results/vagrant/federated-svd/fed/"
project_id = 17305

[debug]
nodeps = true
reinstall = true
timeout = 600


[clients.0]
coordinator = true
fc_username = 'federated.client+00@gmail.com'
data = [
    "data/federated-svd/PRJEB10878/input.csv",
    "configs/vagrant/federated-svd/config.yaml"
]

[clients.1]
fc_username = 'federated.client+01@gmail.com'
data = [
    "data/federated-svd/PRJEB6070/input.csv",
    "configs/vagrant/federated-svd/config.yaml"
]

[clients.2]
fc_username = 'federated.client+02@gmail.com'
data = [
    "data/federated-svd/PRJEB7774/input.csv",
    "configs/vagrant/federated-svd/config.yaml"
]

[clients.3]
fc_username = 'federated.client+03@gmail.com'
data = [
    "data/federated-svd/PRJNA429097/input.csv",
    "configs/vagrant/federated-svd/config.yaml"
]

[clients.4]
fc_username = 'federated.client+04@gmail.com'
data = [
    "data/federated-svd/PRJNA731589/input.csv",
    "configs/vagrant/federated-svd/config.yaml"
]





