[general]

sim = true
project_id = 17285

[clients]

[clients.0]
fc_username = 'p73wzaml9@mozmail.com'
data = ["test_data/randfor_solo/data.csv", "test_data/randfor_solo/config.yml"]
coordinator = true


[debug]

vmonly = false
reinstall = true
nodeps = true



