[general]

sim = true
project_id = 17285
# tool = 'random-forest'


[clients]

[clients.0]
coordinator = true
fc_username = 'p73wzaml9@mozmail.com'
data = [
    "test_data/public_cohorts/PRJEB6070/species.csv",
    "test_data/public_cohorts/PRJEB6070/config.yml"
]


# [clients.1]
# fc_username = 'flxt56ucr@mozmail.com'
# data = [
#     "test_data/public_cohorts/PRJEB7774/species.csv",
#     "test_data/public_cohorts/PRJEB7774/config.yml"
# ]


# [clients.2]
# fc_username = 'tsfl7biss@mozmail.com'
# data = [
#     "test_data/public_cohorts/PRJEB10878/species.csv",
#     "test_data/public_cohorts/PRJEB10878/config.yml"
# ]


# [clients.3]
# fc_username = '@mozmail.com'
# data = [
#     "test_data/public_cohorts/PRJNA429097/species.csv",
#     "test_data/public_cohorts/PRJNA429097/config.yml"
# ]


# [clients.4]
# fc_username = '@mozmail.com'
# data = [
#     "test_data/public_cohorts/PRJNA731589/species.csv",
#     "test_data/public_cohorts/PRJNA731589/config.yml"
# ]



[debug]
vmonly = false
reinstall = true
nodeps = true
timeout = 600



