[general]

sim = true
project_id = 17276


[clients]

[clients.0]
fc_username = 'p73wzaml9@mozmail.com'
data = ["test_data/svd_duo/client0/mnist_200.tsv", "test_data/svd_duo/client0/config.yaml"]
coordinator = true


[clients.1]
fc_username = 'flxt56ucr@mozmail.com'
data = ["test_data/svd_duo/client1/mnist_-200.tsv", "test_data/svd_duo/client1/config.yaml"]





