outdir = "results/biosphere/federated-svd/fed/"
project_id = 17305

[debug]
nodeps = true
reinstall = true
timeout = 600

[[clients]]
coordinator = true
fc_username = "user"
hostname = "host"
username = "ubuntu"
sshkey = "key"
data = ["data/federated-svd/PRJEB10878/input.csv", "configs/biosphere/federated-svd/config.yaml"]

[[clients]]
fc_username = "user"
hostname = "host"
username = "ubuntu"
sshkey = "key"
data = ["data/federated-svd/PRJEB6070/input.csv", "configs/biosphere/federated-svd/config.yaml"]

[[clients]]
fc_username = "user"
hostname = "host"
username = "ubuntu"
sshkey = "key"
data = ["data/federated-svd/PRJEB7774/input.csv", "configs/biosphere/federated-svd/config.yaml"]

[[clients]]
fc_username = "user"
hostname = "host"
username = "ubuntu"
sshkey = "key"
data = ["data/federated-svd/PRJNA429097/input.csv", "configs/biosphere/federated-svd/config.yaml"]

[[clients]]
fc_username = "user"
hostname = "host"
username = "ubuntu"
sshkey = "key"
data = ["data/federated-svd/PRJNA731589/input.csv", "configs/biosphere/federated-svd/config.yaml"]
