outdir = "results/biosphere/federated-svd/cent/"
project_id = 17306

[debug]
nodeps = true
reinstall = true
timeout = 600

[[clients]]
coordinator = true
fc_username = "user"
hostname = "host"
username = "ubuntu"
sshkey = "key"
data = ["data/federated-svd/cent/input.csv", "configs/biosphere/federated-svd/config.yaml"]
