# project accessions to be used in the workflow
accessions: [
  "PRJEB10878",
  "PRJEB6070",
  "PRJEB7774",
  "PRJNA429097",
  "PRJNA731589",
]
# fraction of features to be used
downsample_features: 0.01
# provider of machines
providers: ["biosphere", "vagrant"]
# Names of tools to be run in the workflow
# for each, config files need to be present as:
#      configs/<providers>/<tool>/config_fedsim_cent.toml
#      configs/<providers>/<tool>/config_fedsim_fed.toml
tools: ["federated-svd", "random-forest"] #, "ada-boost"]


