fc_boosting:
  files:
    input: species.csv # name of the input CSV/TSV/sas7bdat file
    output: ada.csv
    missing_data: mean # drop, mean or median

  # parameters
  parameters:
    label_col: health_status
    test_size: 0.3
    n_estimators: 100
    learning_rate: 1
    random_state: 42
    metric: matth # accuracy, roc_auc or matthews_correlation_coefficient. For multi-label this should be accuracy


