[general]

sim = true
outdir = "results/fedsim_cent"
provision_script = 'workflow/FedSim/scripts/provision.sh'
project_id = 17318
# tool = 'ada-boost'


[debug]
nodeps = true
reinstall = false
timeout = 600


[clients]

[clients.0]
coordinator = true
fc_username = 'federated.client+00@gmail.com'
data = [
    "data/public_cohorts/species.csv",
    "resources/ada-boost/config.yml"
]



