fc_logistic_regression:
  input:
    train: "mnist_200.tsv"
    test: "mnist-200.tsv"
  output:
    pred: "pred.csv"
    proba: "proba.csv"
    test: "test.csv"
  format:
    sep: "\t"
    label: "Class"
  split:
    mode: "directory" # directory if cross-validation was used before, else file
    dir: "data" # data if cross-validation app was used before, else .
  algo:
    max_iterations: 10000 # Maximum number of iterations


    